name: Build and Publish

on:
  push:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish-nuget-package:
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Pack
        working-directory: shared
        run: dotnet pack
      - name: Push
        working-directory: shared
        run: |
          dotnet nuget add source --username iKadmium --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/iKadmium/index.json"
          dotnet nuget push "bin/Release/OctocatApp.1.0.0.nupkg" --username iKadmium --password ${{ secrets.GITHUB_TOKEN }} --source "github"
  publish-docker-images:
    strategy:
      matrix:
        include:
          - project: RtpMidiSource
            workdir: sources/RtpMidi
            image-name: source-rtp-midi
          - project: sAcnRenderer
            workdir: renderer/sAcn
            image-name: renderer-sacn
          - project: Processor
            workdir: processor
            image-name: processor
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.image-name }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./${{ matrix.workdir }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}