name: Test and Coverage

on:
  pull_request:
    branches: [ master ]

jobs:
  build-svelte:
    strategy:
      matrix:
        include:
          - project: WebUI
            workdir: webui
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Restore dependencies
        run: pnpm ci
        working-directory: ${{ matrix.workdir }}
      - name: Test
        run: pnpm run test
        working-directory: ${{ matrix.workdir }}
      - name: Build
        run: pnpm run build
        working-directory: ${{ matrix.workdir }}
      - name: Check coverage
        uses: codecov/codecov-action@v1
  build-rust:
    strategy:
      matrix:
        include:
          - project: RtpMidiSource
            workdir: sources/rtpmidi
          # - project: sAcnRenderer
          #   workdir: renderer/sAcn
          - project: NeewerRenderer
            workdir: renderer/neewer
          - project: Processor
            workdir: processor
          - project: WebAPI
            workdir: webapi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: 1.85.0
      - name: Build
        run: cargo build --release
        working-directory: ${{ matrix.workdir }}
      - name: Test
        run: cargo test
        working-directory: ${{ matrix.workdir }}
      - name: Check coverage
        uses: codecov/codecov-action@v1
